name: book_report
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    git: https://github.com/singerdmx/flutter-quill.git

  url_launcher: ^6.2.3
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^9.1.1
  super_clipboard: ^0.8.4

  cupertino_icons: ^1.0.2
  firebase: ^9.0.3
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_database: ^10.2.4
  get: ^4.6.5
  web_browser_detect: ^2.0.3
  file_picker: ^6.1.1

  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  firebase_auth: ^4.7.1
  uuid: ^4.3.3
  intl: ^0.18.1
  encrypt: ^5.0.1
  async: ^2.11.0
  flutter_image_compress: ^2.0.4
  image: ^4.0.17
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - icons/
    - images/

  fonts:
    - family: LINE
      fonts:
        - asset: fonts/LINE-Th.ttf
          weight: 100
        - asset: fonts/LINE-Rg.ttf
          weight: 400
        - asset: fonts/LINE-Bd.ttf
          weight: 700

    - family: MODU
      fonts:
        - asset: fonts/ChildrenModu.ttf

    - family: DREAM
      fonts:
        - asset: fonts/ChildrenDream.ttf

    - family: KYOBO
      fonts:
        - asset: fonts/KyoboHandwriting.ttf

    - family: YEONGDEOK
      fonts:
        - asset: fonts/Yeongdeok-Sea.ttf

    - family: COOKIE
      fonts:
        - asset: fonts/Cookie-Regular.ttf
