name: book_report
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  async: ^2.11.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  encrypt: ^5.0.3
  file_picker: ^6.2.0
  firebase: ^9.0.3
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  firebase_database: ^10.4.8
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_quill: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  http: ^0.13.6
  image: ^4.1.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  super_clipboard: ^0.8.5
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  web_browser_detect: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - icons/
    - images/

  fonts:
    - family: LINE
      fonts:
        - asset: fonts/LINE-Th.ttf
          weight: 100
        - asset: fonts/LINE-Rg.ttf
          weight: 400
        - asset: fonts/LINE-Bd.ttf
          weight: 700

    - family: MODU
      fonts:
        - asset: fonts/ChildrenModu.ttf

    - family: DREAM
      fonts:
        - asset: fonts/ChildrenDream.ttf

    - family: KYOBO
      fonts:
        - asset: fonts/KyoboHandwriting.ttf

    - family: YEONGDEOK
      fonts:
        - asset: fonts/Yeongdeok-Sea.ttf

    - family: COOKIE
      fonts:
        - asset: fonts/Cookie-Regular.ttf
